### ISSUE TITLE
A huge thanks sir 

### ISSUE THREAD

**Issue by SharmagRit** [usmanmughalji/gdriveupload#2]
Hi sir thanks for giving uninstall commands,
But one more issue i faced that is..
Upload speed is stuck at 3mbps restarted server also and did uninstall and installed again..but same 3mpbs upload speed..
But it was not before, it's was going to 25mbps + but not for now..
Don't know what is the actual issue..
If you know what is the issue then please help or guide me..
Thanks a lot.❤️

But there is one more issue i can't install gdrive after install ,
After installing process i can't open the link, I'm stuck here

**Comment by SharmagRit** [comment]
![Screenshot_20220926-131510_JuiceSSH](https://user-images.githubusercontent.com/87909274/192250161-88201e42-cfe8-4f24-adc2-b87143b4c0f4.png)

**Comment by usmanmughalji** [comment]
Please check the new update now and follow the Important note.
